package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activofijo generated by hbm2java
 */
@Entity
@Table(name = "activofijo",
        catalog = "institucion_financiera"
)
public class Activofijo implements java.io.Serializable {

    private int id;
    private Departamento departamento;
    private Sucursal sucursal;
    private Tipoactivo tipoactivo;
    private String nombre;
    private String descripcion;
    private String procedencia;
    private BigDecimal precio;
    private Date fechaadquisicion;
    private Integer vidautil;
    private Integer uso;
    private Set<Activobaja> activobajas = new HashSet<Activobaja>(0);

    public Activofijo() {
    }

    public Activofijo(int id, Departamento departamento, Sucursal sucursal, Tipoactivo tipoactivo, String nombre, String descripcion, String procedencia, BigDecimal precio, Date fechaadquisicion) {
        this.id = id;
        this.departamento = departamento;
        this.sucursal = sucursal;
        this.tipoactivo = tipoactivo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.procedencia = procedencia;
        this.precio = precio;
        this.fechaadquisicion = fechaadquisicion;
    }

    public Activofijo(int id, Departamento departamento, Sucursal sucursal, Tipoactivo tipoactivo, String nombre, String descripcion, String procedencia, BigDecimal precio, Date fechaadquisicion, Integer vidautil, Integer uso, Set<Activobaja> activobajas) {
        this.id = id;
        this.departamento = departamento;
        this.sucursal = sucursal;
        this.tipoactivo = tipoactivo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.procedencia = procedencia;
        this.precio = precio;
        this.fechaadquisicion = fechaadquisicion;
        this.vidautil = vidautil;
        this.uso = uso;
        this.activobajas = activobajas;
    }

    public Activofijo(Departamento departamento, Sucursal sucursal, Tipoactivo tipoactivo, String nombre, String descripcion, String procedencia, BigDecimal precio, Date fechaadquisicion, Integer vidautil, Integer uso) {
        this.departamento = departamento;
        this.sucursal = sucursal;
        this.tipoactivo = tipoactivo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.procedencia = procedencia;
        this.precio = precio;
        this.fechaadquisicion = fechaadquisicion;
        this.vidautil = vidautil;
        this.uso = uso;
    }

    public Activofijo(Departamento departamento, Sucursal sucursal, Tipoactivo tipoactivo, String nombre, String descripcion, String procedencia, BigDecimal precio, Date fechaadquisicion, Integer vidautil) {
        this.departamento = departamento;
        this.sucursal = sucursal;
        this.tipoactivo = tipoactivo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.procedencia = procedencia;
        this.precio = precio;
        this.fechaadquisicion = fechaadquisicion;
        this.vidautil = vidautil;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "iddepartamento", nullable = false)
    public Departamento getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idsucursal", nullable = false)
    public Sucursal getSucursal() {
        return this.sucursal;
    }

    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idtipo", nullable = false)
    public Tipoactivo getTipoactivo() {
        return this.tipoactivo;
    }

    public void setTipoactivo(Tipoactivo tipoactivo) {
        this.tipoactivo = tipoactivo;
    }

    @Column(name = "nombre", nullable = false, length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion", nullable = false, length = 300)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "procedencia", nullable = false, length = 50)
    public String getProcedencia() {
        return this.procedencia;
    }

    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }

    @Column(name = "precio", nullable = false, precision = 10)
    public BigDecimal getPrecio() {
        return this.precio;
    }

    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechaadquisicion", nullable = false, length = 10)
    public Date getFechaadquisicion() {
        return this.fechaadquisicion;
    }

    public void setFechaadquisicion(Date fechaadquisicion) {
        this.fechaadquisicion = fechaadquisicion;
    }

    @Column(name = "vidautil")
    public Integer getVidautil() {
        return this.vidautil;
    }

    public void setVidautil(Integer vidautil) {
        this.vidautil = vidautil;
    }

    @Column(name = "uso")
    public Integer getUso() {
        return this.uso;
    }

    public void setUso(Integer uso) {
        this.uso = uso;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "activofijo")
    public Set<Activobaja> getActivobajas() {
        return this.activobajas;
    }

    public void setActivobajas(Set<Activobaja> activobajas) {
        this.activobajas = activobajas;
    }

}
