package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activobaja generated by hbm2java
 */
@Entity
@Table(name = "activobaja",
         catalog = "institucion_financiera"
)
public class Activobaja implements java.io.Serializable {

    private int id;
    private Activofijo activofijo;
    private String motivo;
    private Date fecha;

    public Activobaja() {
    }

    public Activobaja(int id, Activofijo activofijo, String motivo, Date fecha) {
        this.id = id;
        this.activofijo = activofijo;
        this.motivo = motivo;
        this.fecha = fecha;
    }

    public Activobaja(Activofijo activofijo, String motivo, Date fecha) {
        this.activofijo = activofijo;
        this.motivo = motivo;
        this.fecha = fecha;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idactivo", nullable = false)
    public Activofijo getActivofijo() {
        return this.activofijo;
    }

    public void setActivofijo(Activofijo activofijo) {
        this.activofijo = activofijo;
    }

    @Column(name = "motivo", nullable = false, length = 300)
    public String getMotivo() {
        return this.motivo;
    }

    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha", nullable = false, length = 10)
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
