package entities;
// Generated Jan 20, 2021 9:42:43 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bgeneral generated by hbm2java
 */
@Entity
@Table(name="bgeneral"
    ,catalog="institucion_financiera"
)
public class Bgeneral  implements java.io.Serializable {


     private int id;
     private Cjuridico cjuridico;
     private String cuenta;
     private double monto;
     private int fecha;
     private String clasificacion;

    public Bgeneral() {
    }

    public Bgeneral(int id, Cjuridico cjuridico, String cuenta, double monto, int fecha, String clasificacion) {
       this.id = id;
       this.cjuridico = cjuridico;
       this.cuenta = cuenta;
       this.monto = monto;
       this.fecha = fecha;
       this.clasificacion = clasificacion;
    }

    public Bgeneral(Cjuridico cjuridico, String cuenta, double monto, int fecha, String clasificacion) {
        this.cjuridico = cjuridico;
        this.cuenta = cuenta;
        this.monto = monto;
        this.fecha = fecha;
        this.clasificacion = clasificacion;
    }
    
    
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idcjuridico", nullable=false)
    public Cjuridico getCjuridico() {
        return this.cjuridico;
    }
    
    public void setCjuridico(Cjuridico cjuridico) {
        this.cjuridico = cjuridico;
    }

    
    @Column(name="cuenta", nullable=false, length=200)
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    
    @Column(name="monto", nullable=false, precision=10)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

    
    @Column(name="fecha", nullable=false)
    public int getFecha() {
        return this.fecha;
    }
    
    public void setFecha(int fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="clasificacion", nullable=false, length=100)
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }




}


