package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cjuridico generated by hbm2java
 */
@Entity
@Table(name = "cjuridico",
        catalog = "institucion_financiera"
)
public class Cjuridico implements java.io.Serializable {

    private int id;
    private Persona persona;
    private String codigo;
    private String empresa;
    private String direccion;
    private String telefono;
    private String clasificacion;
    private Set<Bgeneral> bgenerals = new HashSet<Bgeneral>(0);
    private Set<Eresultado> eresultados = new HashSet<Eresultado>(0);

    public Cjuridico() {
    }

    public Cjuridico(int id, Persona persona, String codigo, String empresa, String direccion, String telefono) {
        this.id = id;
        this.persona = persona;
        this.codigo = codigo;
        this.empresa = empresa;
        this.direccion = direccion;
        this.telefono = telefono;
    }

    public Cjuridico(int id, Persona persona, String codigo, String empresa, String direccion, String telefono, String clasificacion, Set<Bgeneral> bgenerals, Set<Eresultado> eresultados) {
        this.id = id;
        this.persona = persona;
        this.codigo = codigo;
        this.empresa = empresa;
        this.direccion = direccion;
        this.telefono = telefono;
        this.clasificacion = clasificacion;
        this.bgenerals = bgenerals;
        this.eresultados = eresultados;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idrepresentate", nullable = false)
    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @Column(name = "codigo", nullable = false, length = 8)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "empresa", nullable = false, length = 300)
    public String getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }

    @Column(name = "direccion", nullable = false, length = 300)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "telefono", nullable = false, length = 9)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "clasificacion", length = 5)
    public String getClasificacion() {
        return this.clasificacion;
    }

    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "cjuridico")
    public Set<Bgeneral> getBgenerals() {
        return this.bgenerals;
    }

    public void setBgenerals(Set<Bgeneral> bgenerals) {
        this.bgenerals = bgenerals;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "cjuridico")
    public Set<Eresultado> getEresultados() {
        return this.eresultados;
    }

    public void setEresultados(Set<Eresultado> eresultados) {
        this.eresultados = eresultados;
    }

}
