package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cnatural generated by hbm2java
 */
@Entity
@Table(name = "cnatural",
        catalog = "institucion_financiera"
)
public class Cnatural implements java.io.Serializable {

    private int id;
    private Persona persona;
    private String codigo;
    private String lugartrabajo;
    private String clasificacion;
    private String tipo;
    private Set<Detallefiador> detallefiadors = new HashSet<Detallefiador>(0);
    private Set<Disponibilidad> disponibilidadsForIdnatural = new HashSet<Disponibilidad>(0);
    private Set<Disponibilidad> disponibilidadsForIdfiador = new HashSet<Disponibilidad>(0);

    public Cnatural() {
    }

    public Cnatural(int id, Persona persona, String codigo, String lugartrabajo, String tipo) {
        this.id = id;
        this.persona = persona;
        this.codigo = codigo;
        this.lugartrabajo = lugartrabajo;
        this.tipo = tipo;
    }

    public Cnatural(int id, Persona persona, String codigo, String lugartrabajo, String clasificacion, String tipo, Set<Detallefiador> detallefiadors, Set<Disponibilidad> disponibilidadsForIdnatural, Set<Disponibilidad> disponibilidadsForIdfiador) {
        this.id = id;
        this.persona = persona;
        this.codigo = codigo;
        this.lugartrabajo = lugartrabajo;
        this.clasificacion = clasificacion;
        this.tipo = tipo;
        this.detallefiadors = detallefiadors;
        this.disponibilidadsForIdnatural = disponibilidadsForIdnatural;
        this.disponibilidadsForIdfiador = disponibilidadsForIdfiador;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idpersona", nullable = false)
    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @Column(name = "codigo", nullable = false, length = 8)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "lugartrabajo", nullable = false, length = 300)
    public String getLugartrabajo() {
        return this.lugartrabajo;
    }

    public void setLugartrabajo(String lugartrabajo) {
        this.lugartrabajo = lugartrabajo;
    }

    @Column(name = "clasificacion", length = 5)
    public String getClasificacion() {
        return this.clasificacion;
    }

    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }

    @Column(name = "tipo", nullable = false, length = 25)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "cnatural")
    public Set<Detallefiador> getDetallefiadors() {
        return this.detallefiadors;
    }

    public void setDetallefiadors(Set<Detallefiador> detallefiadors) {
        this.detallefiadors = detallefiadors;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "cnaturalByIdnatural")
    public Set<Disponibilidad> getDisponibilidadsForIdnatural() {
        return this.disponibilidadsForIdnatural;
    }

    public void setDisponibilidadsForIdnatural(Set<Disponibilidad> disponibilidadsForIdnatural) {
        this.disponibilidadsForIdnatural = disponibilidadsForIdnatural;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "cnaturalByIdfiador")
    public Set<Disponibilidad> getDisponibilidadsForIdfiador() {
        return this.disponibilidadsForIdfiador;
    }

    public void setDisponibilidadsForIdfiador(Set<Disponibilidad> disponibilidadsForIdfiador) {
        this.disponibilidadsForIdfiador = disponibilidadsForIdfiador;
    }

}
