package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallefiador generated by hbm2java
 */
@Entity
@Table(name="detallefiador"
    ,catalog="institucion_financiera"
)
public class Detallefiador  implements java.io.Serializable {


     private int id;
     private Cnatural cnatural;
     private Prestamo prestamo;

    public Detallefiador() {
    }

    public Detallefiador(int id, Cnatural cnatural, Prestamo prestamo) {
       this.id = id;
       this.cnatural = cnatural;
       this.prestamo = prestamo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idfiador", nullable=false)
    public Cnatural getCnatural() {
        return this.cnatural;
    }
    
    public void setCnatural(Cnatural cnatural) {
        this.cnatural = cnatural;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprestamo", nullable=false)
    public Prestamo getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }




}


