package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Disponibilidad generated by hbm2java
 */
@Entity
@Table(name = "disponibilidad",
        catalog = "institucion_financiera"
)
public class Disponibilidad implements java.io.Serializable {

    private int id;
    private Cnatural cnaturalByIdnatural;
    private Cnatural cnaturalByIdfiador;
    private String operacion;
    private double monto;
    private String tipo;

    public Disponibilidad() {
    }

    public Disponibilidad(int id, String operacion, double monto, String tipo) {
        this.id = id;
        this.operacion = operacion;
        this.monto = monto;
        this.tipo = tipo;
    }

    public Disponibilidad(int id, Cnatural cnaturalByIdnatural, Cnatural cnaturalByIdfiador, String operacion, double monto, String tipo) {
        this.id = id;
        this.cnaturalByIdnatural = cnaturalByIdnatural;
        this.cnaturalByIdfiador = cnaturalByIdfiador;
        this.operacion = operacion;
        this.monto = monto;
        this.tipo = tipo;
    }

    public Disponibilidad(Cnatural cnaturalByIdnatural, Cnatural cnaturalByIdfiador, String operacion, double monto, String tipo) {
        this.cnaturalByIdnatural = cnaturalByIdnatural;
        this.cnaturalByIdfiador = cnaturalByIdfiador;
        this.operacion = operacion;
        this.monto = monto;
        this.tipo = tipo;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idnatural")
    public Cnatural getCnaturalByIdnatural() {
        return this.cnaturalByIdnatural;
    }

    public void setCnaturalByIdnatural(Cnatural cnaturalByIdnatural) {
        this.cnaturalByIdnatural = cnaturalByIdnatural;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idfiador")
    public Cnatural getCnaturalByIdfiador() {
        return this.cnaturalByIdfiador;
    }

    public void setCnaturalByIdfiador(Cnatural cnaturalByIdfiador) {
        this.cnaturalByIdfiador = cnaturalByIdfiador;
    }

    @Column(name = "operacion", nullable = false, length = 300)
    public String getOperacion() {
        return this.operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    @Column(name = "monto", nullable = false, precision = 10)
    public double getMonto() {
        return this.monto;
    }

    public void setMonto(double monto) {
        this.monto = monto;
    }

    @Column(name = "tipo", nullable = false, length = 25)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

}
