package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hipoteca generated by hbm2java
 */
@Entity
@Table(name="hipoteca"
    ,catalog="institucion_financiera"
)
public class Hipoteca  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private double monto;
     private Set<Detallehipoteca> detallehipotecas = new HashSet<Detallehipoteca>(0);

    public Hipoteca() {
    }

	
    public Hipoteca(int id, String nombre, String descripcion, double monto) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.monto = monto;
    }
    public Hipoteca(int id, String nombre, String descripcion, double monto, Set<Detallehipoteca> detallehipotecas) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.monto = monto;
       this.detallehipotecas = detallehipotecas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="monto", nullable=false, precision=10)
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hipoteca")
    public Set<Detallehipoteca> getDetallehipotecas() {
        return this.detallehipotecas;
    }
    
    public void setDetallehipotecas(Set<Detallehipoteca> detallehipotecas) {
        this.detallehipotecas = detallehipotecas;
    }




}


