package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona",
        catalog = "institucion_financiera"
)
public class Persona implements java.io.Serializable {

    private int id;
    private String dui;
    private String nombre;
    private String apellido;
    private String sexo;
    private String telefono;
    private String direccion;
    private String estadocivil;
    private Date fechanacimiento;
    private String tipo;
    private Set<Cnatural> cnaturals = new HashSet<Cnatural>(0);
    private Set<Detallecartera> detallecarteras = new HashSet<Detallecartera>(0);
    private Set<Cjuridico> cjuridicos = new HashSet<Cjuridico>(0);
    private Set<Carterageneral> carteragenerals = new HashSet<Carterageneral>(0);
    private Set<Usuario> usuarios = new HashSet<Usuario>(0);
    private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Persona() {
    }

    public Persona(int id, String dui, String nombre, String apellido, String sexo, String telefono, String direccion, String estadocivil, Date fechanacimiento, String tipo) {
        this.id = id;
        this.dui = dui;
        this.nombre = nombre;
        this.apellido = apellido;
        this.sexo = sexo;
        this.telefono = telefono;
        this.direccion = direccion;
        this.estadocivil = estadocivil;
        this.fechanacimiento = fechanacimiento;
        this.tipo = tipo;
    }

    public Persona(int id, String dui, String nombre, String apellido, String sexo, String telefono, String direccion, String estadocivil, Date fechanacimiento, String tipo, Set<Cnatural> cnaturals, Set<Detallecartera> detallecarteras, Set<Cjuridico> cjuridicos, Set<Carterageneral> carteragenerals, Set<Usuario> usuarios, Set<Prestamo> prestamos) {
        this.id = id;
        this.dui = dui;
        this.nombre = nombre;
        this.apellido = apellido;
        this.sexo = sexo;
        this.telefono = telefono;
        this.direccion = direccion;
        this.estadocivil = estadocivil;
        this.fechanacimiento = fechanacimiento;
        this.tipo = tipo;
        this.cnaturals = cnaturals;
        this.detallecarteras = detallecarteras;
        this.cjuridicos = cjuridicos;
        this.carteragenerals = carteragenerals;
        this.usuarios = usuarios;
        this.prestamos = prestamos;
    }

    public Persona(String dui, String nombre, String apellido, String sexo, String telefono, String direccion, String estadocivil, Date fechanacimiento, String tipo) {
        this.dui = dui;
        this.nombre = nombre;
        this.apellido = apellido;
        this.sexo = sexo;
        this.telefono = telefono;
        this.direccion = direccion;
        this.estadocivil = estadocivil;
        this.fechanacimiento = fechanacimiento;
        this.tipo = tipo;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "dui", nullable = false, length = 10)
    public String getDui() {
        return this.dui;
    }

    public void setDui(String dui) {
        this.dui = dui;
    }

    @Column(name = "nombre", nullable = false, length = 25)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "apellido", nullable = false, length = 25)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Column(name = "sexo", nullable = false, length = 15)
    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Column(name = "telefono", nullable = false, length = 9)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "direccion", nullable = false, length = 300)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "estadocivil", nullable = false, length = 25)
    public String getEstadocivil() {
        return this.estadocivil;
    }

    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechanacimiento", nullable = false, length = 10)
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }

    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    @Column(name = "tipo", nullable = false, length = 20)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
    public Set<Cnatural> getCnaturals() {
        return this.cnaturals;
    }

    public void setCnaturals(Set<Cnatural> cnaturals) {
        this.cnaturals = cnaturals;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
    public Set<Detallecartera> getDetallecarteras() {
        return this.detallecarteras;
    }

    public void setDetallecarteras(Set<Detallecartera> detallecarteras) {
        this.detallecarteras = detallecarteras;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
    public Set<Cjuridico> getCjuridicos() {
        return this.cjuridicos;
    }

    public void setCjuridicos(Set<Cjuridico> cjuridicos) {
        this.cjuridicos = cjuridicos;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
    public Set<Carterageneral> getCarteragenerals() {
        return this.carteragenerals;
    }

    public void setCarteragenerals(Set<Carterageneral> carteragenerals) {
        this.carteragenerals = carteragenerals;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persona")
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }

    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }

}
