package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "sucursal",
        catalog = "institucion_financiera"
)
public class Sucursal implements java.io.Serializable {

    private int id;
    private String nombre;
    private String codigo;
    private Set<Activofijo> activofijos = new HashSet<Activofijo>(0);
    private Set<Carterageneral> carteragenerals = new HashSet<Carterageneral>(0);

    public Sucursal() {
    }

    public Sucursal(String nombre, String codigo) {
        this.nombre = nombre;
        this.codigo = codigo;
    }

    public Sucursal(int id, String nombre, String codigo) {
        this.id = id;
        this.nombre = nombre;
        this.codigo = codigo;
    }

    public Sucursal(int id, String nombre, String codigo, Set<Activofijo> activofijos, Set<Carterageneral> carteragenerals) {
        this.id = id;
        this.nombre = nombre;
        this.codigo = codigo;
        this.activofijos = activofijos;
        this.carteragenerals = carteragenerals;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nombre", nullable = false, length = 25)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "codigo", nullable = false, length = 5)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "sucursal")
    public Set<Activofijo> getActivofijos() {
        return this.activofijos;
    }

    public void setActivofijos(Set<Activofijo> activofijos) {
        this.activofijos = activofijos;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "sucursal")
    public Set<Carterageneral> getCarteragenerals() {
        return this.carteragenerals;
    }

    public void setCarteragenerals(Set<Carterageneral> carteragenerals) {
        this.carteragenerals = carteragenerals;
    }

}
