package entities;
// Generated Dec 30, 2020 2:22:52 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoprestamo generated by hbm2java
 */
@Entity
@Table(name = "tipoprestamo",
         catalog = "institucion_financiera"
)
public class Tipoprestamo implements java.io.Serializable {

    private int id;
    private String tipo;
    private double porcentaje;
    private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Tipoprestamo() {
    }

    public Tipoprestamo(int id, String tipo, double porcentaje) {
        this.id = id;
        this.tipo = tipo;
        this.porcentaje = porcentaje;
    }

    public Tipoprestamo(int id, String tipo, double porcentaje, Set<Prestamo> prestamos) {
        this.id = id;
        this.tipo = tipo;
        this.porcentaje = porcentaje;
        this.prestamos = prestamos;
    }

    public Tipoprestamo(String tipo, double porcentaje) {
        this.tipo = tipo;
        this.porcentaje = porcentaje;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "tipo", nullable = false, length = 200)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Column(name = "porcentaje", nullable = false, precision = 10)
    public double getPorcentaje() {
        return this.porcentaje;
    }

    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tipoprestamo")
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }

    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }

}
